-- EXPERIMENT-7(b)
-- PROGRAM 1: CALCULATE ANNUAL SALARY USING A STORED FUNCTION

SET SERVEROUTPUT ON;

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE3
(
    EMPLOYEE_ID NUMBER(4) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(30),
    MONTHLY_SALARY NUMBER(10,2)
);

-- Insert sample employee records
INSERT INTO EMPLOYEE3 VALUES (101, 'Ravi', 25000);
INSERT INTO EMPLOYEE3 VALUES (102, 'Priya', 30000);
INSERT INTO EMPLOYEE3 VALUES (103, 'Arjun', 28000);
INSERT INTO EMPLOYEE3 VALUES (104, 'Sneha', 35000);
INSERT INTO EMPLOYEE3 VALUES (105, 'Kiran', 40000);

-- Save the records
COMMIT;

-- Create stored function
CREATE OR REPLACE FUNCTION CALCULATE_ANNUAL_SALARY
(
    P_MONTHLY_SALARY IN NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN P_MONTHLY_SALARY * 12;
END;
/

-- Invoke the function using SQL SELECT statement
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       MONTHLY_SALARY,
       CALCULATE_ANNUAL_SALARY(MONTHLY_SALARY) AS ANNUAL_SALARY
FROM EMPLOYEE3;