-- EXPERIMENT-7(b)
-- PROGRAM 2: FIND THE TOTAL NUMBER OF STUDENTS IN A COURSE

SET SERVEROUTPUT ON;

-- Create STUDENT12 table

CREATE TABLE STUDENT13
(
    STUDENT_ID NUMBER(4) PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30),
    COURSE VARCHAR2(20),
    MARKS NUMBER(3)
);

-- Insert sample student records

INSERT INTO STUDENT13 VALUES (101, 'Rahul', 'B.Tech', 82);
INSERT INTO STUDENT13 VALUES (102, 'Sneha', 'B.Tech', 74);
INSERT INTO STUDENT13 VALUES (103, 'Arjun', 'BCA', 58);
INSERT INTO STUDENT13 VALUES (104, 'Priya', 'B.Sc', 91);
INSERT INTO STUDENT13 VALUES (105, 'Kiran', 'BCA', 45);

-- Save records

COMMIT;


-- Create stored function

CREATE OR REPLACE FUNCTION COUNT_STUDENTS
(
    P_COURSE IN VARCHAR2
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO V_TOTAL
    FROM STUDENT13
    WHERE COURSE = P_COURSE;

    RETURN V_TOTAL;

END;
/

-- Invoke the function using SQL SELECT statement

SELECT 'B.Tech' AS COURSE,
       COUNT_STUDENTS('B.Tech') AS TOTAL_STUDENTS
FROM DUAL;

SELECT 'BCA' AS COURSE,
       COUNT_STUDENTS('BCA') AS TOTAL_STUDENTS
FROM DUAL;