CREATE TABLE STUDENT1(
name VARCHAR2(20),
student_number NUMBER,
class NUMBER,
major VARCHAR2(20));

INSERT INTO STUDENT1 VALUES('smith',17,1,'CS');
INSERT INTO STUDENT1 VALUES('brown',8,2,'CS');

SELECT * FROM STUDENT1;


CREATE TABLE COURSE2(
course_name VARCHAR2(50),
course_number VARCHAR2(20),
credit_hours NUMBER,
Department VARCHAR2(20));

INSERT INTO COURSE2
VALUES('intro to computer science','CS1310',4,'CS');

SELECT *FROM COURSE2;

INSERT INTO COURSE2
VALUES('data structures','CS3320',4,'CS');

SELECT *FROM COURSE2;

INSERT INTO COURSE2
VALUES('discrete mathematics','MATH2410',3,'MATH');

SELECT *FROM COURSE2;

INSERT INTO COURSE2
VALUES('database','CS3380',3,'CS');

SELECT *FROM COURSE2;


CREATE TABLE section2(
section_id NUMBER,
course_number VARCHAR2(20),
semester VARCHAR2(20),
year NUMBER,
instructor VARCHAR2(20));

INSERT INTO section2
VALUES(85,'MATH2410','FALL',07,'KING');
INSERT INTO section2
VALUES(92,'CS1310','FALL',07,'Anderson');
INSERT INTO section2
VALUES(102,'CS3320','SPRING',08,'KNUTH');
INSERT INTO section2
VALUES(112,'MATH2410','FALL',08,'CHANG');
INSERT INTO section2
VALUES(119,'CS1310','FALL',08,'ANDERSON');
INSERT INTO section2
VALUES(135,'CS3380','FALL',08,'STONE');

SELECT *FROM section2;

CREATE TABLE GRADE_REPORT1(
student_number NUMBER,
section_identifier NUMBER,
grade VARCHAR2(20));

INSERT INTO GRADE_REPORT1 VALUES(17,112,'B');
INSERT INTO GRADE_REPORT1 VALUES(17,119,'C');
INSERT INTO GRADE_REPORT1 VALUES(8,85,'A');
INSERT INTO GRADE_REPORT1 VALUES(8,92,'A');
INSERT INTO GRADE_REPORT1 VALUES(8,102,'B');
INSERT INTO GRADE_REPORT1 VALUES(8,135,'A');

SELECT * FROM GRADE_REPORT1;

