SET SERVEROUTPUT ON;

-- Create base EMPLOYEE table
CREATE TABLE EMPLOYEE18
(
    EMPLOYEE_ID NUMBER(4) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(30),
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER(10,2)
);

-- Insert sample records
INSERT INTO EMPLOYEE18 VALUES (101, 'Rahul', 'HR', 35000);
INSERT INTO EMPLOYEE18 VALUES (102, 'Sneha', 'Sales', 42000);
INSERT INTO EMPLOYEE18 VALUES (103, 'Arjun', 'Finance', 45000);

COMMIT;

-- Create view
CREATE OR REPLACE VIEW EMPLOYEE_VIEW AS
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY
FROM EMPLOYEE18;

-- Create INSTEAD OF UPDATE trigger
CREATE OR REPLACE TRIGGER TRG_UPDATE_VIEW
INSTEAD OF UPDATE
ON EMPLOYEE_VIEW
FOR EACH ROW
BEGIN
    UPDATE EMPLOYEE18
    SET EMPLOYEE_NAME = :NEW.EMPLOYEE_NAME,
        DEPARTMENT = :NEW.DEPARTMENT,
        SALARY = :NEW.SALARY
    WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;

    DBMS_OUTPUT.PUT_LINE(
        'Employee record updated through the view.'
    );
END;
/

-- Update employee through the view
UPDATE EMPLOYEE_VIEW
SET SALARY = 40000
WHERE EMPLOYEE_ID = 101;

COMMIT;

-- Display base table
SELECT EMPLOYEE_ID,
       EMPLOYEE_NAME,
       DEPARTMENT,
       SALARY
FROM EMPLOYEE18;